export enum RestrictionType {

    PUBLIC_TRANSPORTATION = 'PUBLIC_TRANSPORTATION',
    EVENTS_AND_ASSEMBLIES = 'EVENTS_AND_ASSEMBLIES',
    GASTRONOMY = 'GASTRONOMY',
    PUBLIC_PLACES = 'PUBLIC_PLACES',
    RETAIL = 'RETAIL',
    CURFEW = 'CURFEW',
  }